version: '3'

services:
  frontend:
    build:
      context: ./web
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./server
    ports:
      - "4000:4000"
