version: '3'

services:
  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "4000:4000"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - /var/app/current:/var/app:ro
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - frontend
      - backend